### ISSUE TITLE
Harmonise privacy group modes between Besu doc and Tessera doc 

### ISSUE THREAD

**Issue by MadelineMurray** [ConsenSys/doc.tessera#50]
In the Besu docs, the privacy groups stored in Orion are called EEA-privacy and Besu-enhanced privacy.  Relevant doc: https://besu.hyperledger.org/en/stable/Concepts/Privacy/Privacy-Groups/ 

In the Tessera docs, the same privacy group are called Legacy and Pantheon privacy groups. https://docs.tessera.consensys.net/en/latest/Concepts/Privacy-Groups/

The clearest way to resolve may be to remove the explanations from the Tessera docs - if the equivalent content is in the Besu docs and wasn't included in the Orion docs, it's not needed in the Tessera docs.

**Comment by Krish1979** [comment]
The Tessera docs is not just pertaining to Besu, privacy group is available for all clients including goquorum. So I would leave the contents in there for now.
