### ISSUE TITLE
Generate and host Tessera Swagger API

### ISSUE THREAD

**Issue by NicolasMassart** [ConsenSys/doc.tessera#7]
## Describe the bug

The source for https://jpmorganchase.github.io/tessera-swagger/ currently hosted on GithubPages is https://github.com/jpmorganchase/jpmorganchase.github.io/tree/master/tessera-swagger and the Swagger is manually generated.
The https://github.com/jpmorganchase/jpmorganchase.github.io won't be moved to Consensys.

NOTE: this repos also hosts the Quorum Remix plugin

## Expected behavior

- [ ] Have a CI generated API doc hosted alongside Tessera doc site

**Comment by Krish1979** [comment]
Until there is a CI process in place , the interim solution is to host the swagger page under Consensus organisation: 

a) copy https://github.com/jpmorganchase/jpmorganchase.github.io/tree/master/tessera-swagger folder to  https://github.com/consensys/consensys.github.io/

b) update the hosting path in https://github.com/ConsenSys/doc.tessera/edit/master/docs/Reference/REST-API.md to "https://consensys.github.io/tessera-swagger/index.html#/"

**Comment by NicolasMassart** [comment]
I think we are going to host it directly on the tessera doc site Github Pages site.

**Comment by NicolasMassart** [comment]
API doc is now hosted on Github Pages in this repos gh-pages branch and published on https://consensys.github.io/doc.tessera/
