### ISSUE TITLE
Docs migration - Styling updates

### ISSUE THREAD

**Issue by Krish1979** [ConsenSys/doc.tessera#9]
Here are some suggested changes to improve readability:
- [x] https://docs.tessera.consensys.net/en/latest/HowTo/Configure/Tessera/#server - Paragraph starting “Note that there are two configuration entries relating to the server address…” has an incorrectly formatted list. This is carried over from previous docs.. It needs a blank line added to sort the format.
- [x] https://docs.tessera.consensys.net/en/latest/Concepts/Transaction-manager/ - link to lifecycle image is broken and needs to be corrected.
- [x] https://docs.tessera.consensys.net/en/latest/HowTo/Configure/Keys/ - formatting for the different configuration `tabs` across the page is broken
- [x] ConsenSys/quorum#1047 - The updates to the sample config as part of latest release are not present in the relevant section

Once above documentation updates are completed along with ConsenSys/doc.goquorum#11, PR ConsenSys/quorum#1062 to delete old documentation could be merged.

**Comment by MadelineMurray** [comment]
@NicolasMassart - are you able to have a look at these?  I think the broken link should probably be pointing to: 
https://docs.goquorum.consensys.net/en/latest/Concepts/Privacy/PrivateTransactionLifecycle/

I'm not 100% sure about the last point without digging into it - pass it back to me if it's not clear how to fix.

**Comment by chris-j-h** [comment]
- [ ] There is another use of `tabs` that is formatted incorrectly here - https://docs.tessera.consensys.net/en/latest/HowTo/Generate-keys/#file-stored-keys
