### ISSUE TITLE
Clarify that Tessera must be available at the time a transaction is sent 

### ISSUE THREAD

**Issue by bgravenorst** [ConsenSys/doc.tessera#99]
[Comment on technical-support channel](https://go-quorum.slack.com/archives/C825QTQ1Z/p1628074884001900)

> All private transaction managers (Tessera) participating to a private transaction (in privateFor) must be available at the time the transaction is sent. If some Tessera are not available then you receive an error and the transaction is not propagated network.
To handle those cases, you can set-up a retry strategy. This is not automated so you should define the best retry strategy based on your needs.
This is to make sure that all private participants have received the private payload before the transaction is propagated to the network. This is an important protection to avoid ending up in situation where nodes could miss some transactions that they were expected to participate to. 

Add documentation to clarify this behavior, and if required add documentation regarding how to set up a retry strategy.

**Comment by rolandtyler** [comment]
closed to #148
